version: "3.8"

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
    networks:
      - telemetry-net

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - telemetry-net
    depends_on:
      - zookeeper

  producer:
    build: ./producer
    container_name: telemetry_producer
    ports:
      - "8080:8080"
    networks:
      - telemetry-net
    depends_on:
      - kafka

  consumer:
    build: ./consumer
    container_name: telemetry_consumer
    ports:
      - "8081:8081"
    networks:
      - telemetry-net
    depends_on:
      - kafka
      - db

  viewer:
    build: ./viewer
    container_name: telemetry_viewer
    ports:
      - "8082:8082"
    networks:
      - telemetry-net
    depends_on:
      - db

  db:
    build: ./db
    container_name: telemetry_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: telemetrydb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - telemetry-net

networks:
  telemetry-net:
    driver: bridge

volumes:
  db-data:
